### ISSUE TITLE
Saved data

### ISSUE THREAD

**Issue by jjw24** [lostping/Flow.Launcher.Plugin.Kitty#4]
Hey how's it going, just saw this in your release notes:
`'Portable Kitty is now saved to plugin settings folder by default to keep the sessions.
Due to how the Flow launcher update process works, the portable KiTTY-Sessions would be wiped on every plugin update.'`, you can save the sessions in the settings folder in `.. FlowLauncher\Settings\Plugins\`, updating the plugin wouldn't touch this folder.

**Comment by lostping** [comment]
Hey!

The problem was that I did save the portable executable automatically to the plugin folder.
(The portable executable save all sessions to the folder where the executable resides.)
My initial thought was: Hey, so if uninstalled the executable gets removed, too.
I didn't realize that an update also does replace the plugin folder (thus removing all KiTTY sessions).

The current change does exactly this, it saves the portable executable to User Settings, i. e. `UserData\Settings\Plugins\Flow.Launcher.Plugin.Kitty`
